# Generated by Django 6.0.3 on 2026-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='', verbose_name='프로필사진')),
                ('nickname', models.CharField(verbose_name='닉네임')),
                ('username', models.CharField(verbose_name='사용자이름')),
                ('post_count', models.PositiveIntegerField(verbose_name='게시물개수')),
                ('following_count', models.PositiveIntegerField(verbose_name='팔로잉수')),
                ('follower_count', models.PositiveIntegerField(verbose_name='팔로워수')),
            ],
        ),
    ]
