# Generated by Django 6.0.5 on 2026-05-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='제목')),
                ('author', models.TextField(verbose_name='저자')),
                ('rate', models.PositiveIntegerField(verbose_name='평점')),
            ],
        ),
    ]
