# Generated by Django 6.0.5 on 2026-05-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='text',
            field=models.TextField(default='', verbose_name='독후감'),
            preserve_default=False,
        ),
    ]
